version: '2'
services:
    discovery:
        image: jsmontoya05/discovery:1
        container_name: discovery
        ports:
            - "8762:8762"
        networks:
            - app-network
    gateway:
        image: jsmontoya05/gateway:1
        container_name: gateway
        ports:
            - "8080:8080"
        depends_on:
            - "discovery"
        environment:
            - JAVA_OPTS=
                -DEUREKA_SERVER=http://172.22.0.2:8762/eureka
        networks:
            - app-network
    balancer:
        image: jsmontoya05/balancer:1
        container_name: balancer
        depends_on:
            - discovery
            - gateway
        environment:
            - JAVA_OPTS=
                -DEUREKA_SERVER=http://172.22.0.2:8762/eureka
        networks:
            - app-network
    api_service:
        image: jsmontoya05/apiservice:1
        depends_on:
            - discovery
            - gateway
        environment:
            - JAVA_OPTS=
                -DEUREKA_SERVER=http://172.22.0.2:8762/eureka
        networks:
            - app-network
        deploy:
            replicas: 3


networks:
  app-network:
    ipam:
      config:
        - subnet: 172.22.0.0/16
